name: ultrack-plant-seg
channels:
  - pytorch
  - gurobi
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - coin-or-cbc
  - cucim
  - cupy
  - cpuonly
  - gurobi
  - jupyter
  - pyqt
  - pytorch
  - plant-seg
  - napari
  - napari-ome-zarr
