name: ultrack-plant-seg
channels:
  - pytorch
  - nvidia
  - gurobi
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - coin-or-cbc
  - cucim
  - cupy!=13.*
  - gurobi
  - jupyter
  - pyqt
  - pytorch
  - pytorch-cuda=12.1
  - cudnn
  - plant-seg
  - napari
  - napari-ome-zarr
