# Reference: napari/napari github workflows
name: test PR

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]
    branches:
      - main
  pull_request_review:
    types: [submitted]

jobs:
  test:
    name: ${{ matrix.platform }} py${{ matrix.python }} ${{ matrix.backend }}
    if: github.event.pull_request.draft == false
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-latest
            python: "3.11"
            backend: pyside6
            coverage: true
          - platform: ubuntu-latest
            python: "3.12"
            backend: pyqt5
          - platform: ubuntu-latest
            python: "3.13"
            backend: pyqt5
          - platform: macos-latest
            python: "3.13"
            backend: pyqt5
          - platform: windows-latest
            python: "3.13"
            backend: pyqt5

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v4

      # see https://github.com/actions/runner-images/issues/709#issuecomment-612569242
      - name: Workaround to free up space on github runner
        if: runner.os == 'Linux'
        run: sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python }}
          enable-cache: true

      - name: Setup headless display
        if: runner.os == 'Linux'
        uses: pyvista/setup-headless-display-action@5bc8de3bc71fcda7a96439571287a554901541a0 # v4.3
        with:
          qt: true
          wm: herbstluftwm

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -e ".[test,ml]" "${{ matrix.backend }}"

      - name: Run pre-commit
        run: uvx pre-commit run --all-files

      - name: Testing
        run: uv run pytest -v --color=yes --cov=ultrack --cov-report=xml --durations=15 .
        env:
          PLATFORM: ${{ matrix.platform }}
          BACKEND: ${{ matrix.backend }}

      - name: Coverage
        if: ${{ matrix.coverage }}
        uses: codecov/codecov-action@v6
